### PR TITLE
Dataverse data access module

### PR DESCRIPTION
**Pull request by abearab**
### Aim
Including a draft [dataverse](https://dataverse.harvard.edu/) data collector as part of `gget` tool boxes. 

e.g.
```bash
gget dataverse -t dataverse.tsv -o path-to-dir
```

```python
import gget
# df table with `id`, `name`, and `type` columns
gget.dataverse(df = df,  path = 'path-to-dir')
```

### Tasks 
- [x] make a python module and CLI for data collection from dataverse
- [x] collect data for a list of datasets defined as a JSON
- ~build a JSON file for a list of datasets deposited in a given dataverse DOI at certain version~
- ~collect data by providing a dataverse DOI and version~
- [x] collect data by providing a list of dataverse datafiles (i.e. `id`, `name`, and `type`) in dataframe or `csv`/`tsv` file
- [ ] collect data by providing a list of dataverse datafiles (i.e. `id`, `name`, and `type`) as arguments

### History
As part of https://github.com/GilbertLabUCSF/CanDI/issues/34, related to #121, I draft a module to collect data from [dataverse](https://dataverse.harvard.edu/). Then I thought data collection from dataverse can be a more general functionality here as part of `gget`.

I mostly borrowed codes from [gears/utils.py](https://github.com/snap-stanford/GEARS/blob/master/gears/utils.py) or [TDC/load.py](https://github.com/mims-harvard/TDC/blob/main/tdc/utils/load.py). However, there are other efforts such as [pyDataverse](https://github.com/gdcc/pyDataverse) and [easyDataverse](https://github.com/gdcc/easyDataverse).

### References
- https://guides.dataverse.org/en/latest/api/dataaccess.html
- https://github.com/mims-harvard/TDC/blob/main/tdc/utils/load.py

### CODE REVIEW

**Comment by abearab** [comment]
cc @amva13

**Comment by lauraluebbert** [comment]
Hi Abe, this is great work, thank you! I'm pretty busy right now but I'll try to start merging asap. 

I just have two thoughts at the moment:
1. We'll need to add unittests for this module. Do you have any ideas on how they should look like?
2. Having a json file as input is a relatively complex input type. Is there perhaps a way around this to simplify the input to the module?

**Comment by abearab** [comment]
Hi Laura,

> 1. We'll need to add unittests for this module. Do you have any ideas on how they should look like?

I'll think about and add more commits asap.

> 2. Having a json file as input is a relatively complex input type. Is there perhaps a way around this to simplify the input to the module?

That's true. I think this can work with dataverse DOI and/or just `fileId`. However, I personally think a json file can be a good option to list all files related to a single project or topic. I'll try to add more commits in this regard. 

I made this a draft PR while I'm adding more commits.

**Comment by lauraluebbert** [comment]
Oops sorry didn't mean to close this

**Comment by abearab** [comment]
> Oops sorry didn't mean to close this

Oh no worries, I also didn't get chance to finish what we discussed before. I have the changes in a fork so I'll open another PR in the future. Thanks :)

**Comment by lauraluebbert** [comment]
No need, I'll reopen this one as soon as the unit tests are passing and I can make a new dev branch

**Comment by lauraluebbert** [comment]
I did it again lol sorry

**Comment by abearab** [comment]
https://github.com/mims-harvard/TDC/issues/314#issuecomment-2396435932

**Pull request closed without merging**
